# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dcs.mission.v0 import mission_pb2 as dcs_dot_mission_dot_v0_dot_mission__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dcs/mission/v0/mission_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MissionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMissionMetadata = channel.unary_unary(
                '/dcs.mission.v0.MissionService/GetMissionMetadata',
                request_serializer=dcs_dot_mission_dot_v0_dot_mission__pb2.MissionMetadataRequest.SerializeToString,
                response_deserializer=dcs_dot_mission_dot_v0_dot_mission__pb2.MissionMetadata.FromString,
                _registered_method=True)
        self.StreamUnits = channel.unary_stream(
                '/dcs.mission.v0.MissionService/StreamUnits',
                request_serializer=dcs_dot_mission_dot_v0_dot_mission__pb2.StreamUnitsRequest.SerializeToString,
                response_deserializer=dcs_dot_mission_dot_v0_dot_mission__pb2.UnitEvent.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/dcs.mission.v0.MissionService/StreamEvents',
                request_serializer=dcs_dot_mission_dot_v0_dot_mission__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=dcs_dot_mission_dot_v0_dot_mission__pb2.MissionEvent.FromString,
                _registered_method=True)


class MissionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMissionMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUnits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMissionMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMissionMetadata,
                    request_deserializer=dcs_dot_mission_dot_v0_dot_mission__pb2.MissionMetadataRequest.FromString,
                    response_serializer=dcs_dot_mission_dot_v0_dot_mission__pb2.MissionMetadata.SerializeToString,
            ),
            'StreamUnits': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamUnits,
                    request_deserializer=dcs_dot_mission_dot_v0_dot_mission__pb2.StreamUnitsRequest.FromString,
                    response_serializer=dcs_dot_mission_dot_v0_dot_mission__pb2.UnitEvent.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=dcs_dot_mission_dot_v0_dot_mission__pb2.StreamEventsRequest.FromString,
                    response_serializer=dcs_dot_mission_dot_v0_dot_mission__pb2.MissionEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcs.mission.v0.MissionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dcs.mission.v0.MissionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MissionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMissionMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.mission.v0.MissionService/GetMissionMetadata',
            dcs_dot_mission_dot_v0_dot_mission__pb2.MissionMetadataRequest.SerializeToString,
            dcs_dot_mission_dot_v0_dot_mission__pb2.MissionMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dcs.mission.v0.MissionService/StreamUnits',
            dcs_dot_mission_dot_v0_dot_mission__pb2.StreamUnitsRequest.SerializeToString,
            dcs_dot_mission_dot_v0_dot_mission__pb2.UnitEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dcs.mission.v0.MissionService/StreamEvents',
            dcs_dot_mission_dot_v0_dot_mission__pb2.StreamEventsRequest.SerializeToString,
            dcs_dot_mission_dot_v0_dot_mission__pb2.MissionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
