# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dcs/mission/v0/mission.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dcs/mission/v0/mission.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dcs.common.v0 import common_pb2 as dcs_dot_common_dot_v0_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x64\x63s/mission/v0/mission.proto\x12\x0e\x64\x63s.mission.v0\x1a\x1a\x64\x63s/common/v0/common.proto\"\x18\n\x16MissionMetadataRequest\"N\n\x0fMissionMetadata\x12\x0f\n\x07theater\x18\x01 \x01(\t\x12\x14\n\x0cmission_name\x18\x02 \x01(\t\x12\x14\n\x0cmission_time\x18\x03 \x01(\t\":\n\x12StreamUnitsRequest\x12\x11\n\tpoll_rate\x18\x01 \x01(\x01\x12\x11\n\tcoalition\x18\x02 \x01(\t\"v\n\tUnitEvent\x12\x0f\n\x07unit_id\x18\x01 \x01(\t\x12\x11\n\tcoalition\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0b\n\x03lat\x18\x05 \x01(\x01\x12\x0b\n\x03lng\x18\x06 \x01(\x01\x12\x0b\n\x03\x61lt\x18\x07 \x01(\x01\"\x15\n\x13StreamEventsRequest\"\\\n\x0cMissionEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x11\n\tcoalition\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t2\x94\x02\n\x0eMissionService\x12]\n\x12GetMissionMetadata\x12&.dcs.mission.v0.MissionMetadataRequest\x1a\x1f.dcs.mission.v0.MissionMetadata\x12N\n\x0bStreamUnits\x12\".dcs.mission.v0.StreamUnitsRequest\x1a\x19.dcs.mission.v0.UnitEvent0\x01\x12S\n\x0cStreamEvents\x12#.dcs.mission.v0.StreamEventsRequest\x1a\x1c.dcs.mission.v0.MissionEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dcs.mission.v0.mission_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MISSIONMETADATAREQUEST']._serialized_start=76
  _globals['_MISSIONMETADATAREQUEST']._serialized_end=100
  _globals['_MISSIONMETADATA']._serialized_start=102
  _globals['_MISSIONMETADATA']._serialized_end=180
  _globals['_STREAMUNITSREQUEST']._serialized_start=182
  _globals['_STREAMUNITSREQUEST']._serialized_end=240
  _globals['_UNITEVENT']._serialized_start=242
  _globals['_UNITEVENT']._serialized_end=360
  _globals['_STREAMEVENTSREQUEST']._serialized_start=362
  _globals['_STREAMEVENTSREQUEST']._serialized_end=383
  _globals['_MISSIONEVENT']._serialized_start=385
  _globals['_MISSIONEVENT']._serialized_end=477
  _globals['_MISSIONSERVICE']._serialized_start=480
  _globals['_MISSIONSERVICE']._serialized_end=756
# @@protoc_insertion_point(module_scope)
